# Generated by Django 6.0 on 2026-01-06 07:39

import apps.assets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0002_deliverabletemplate_event_eventdeliverable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file', upload_to=apps.assets.models.asset_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image (JPG/PNG/WebP)'), ('video', 'Video (MP4/MOV)'), ('pdf', 'PDF Document'), ('other', 'Other')], default='image', max_length=10)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True, help_text='Notes about this asset version')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this asset version is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliverable', models.ForeignKey(blank=True, help_text='The deliverable this asset belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='planning.eventdeliverable')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
