# Generated by Django 6.0 on 2026-01-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the theme (e.g., 'Cyberpunk', 'Eden Reborn')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the theme aesthetic and mood')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month this theme applies to')),
                ('year', models.PositiveIntegerField(help_text='Year this theme applies to')),
                ('primary_color', models.CharField(blank=True, default='#d946ef', help_text='Primary hex color for the theme (e.g., #d946ef)', max_length=7)),
                ('accent_color', models.CharField(blank=True, default='#22d3ee', help_text='Accent hex color for the theme', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this theme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Period',
                'verbose_name_plural': 'Theme Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
