# Generated by Django 6.0 on 2026-01-06 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the deliverable (e.g., 'Cube LED Video', 'Poster A3')", max_length=100)),
                ('specs', models.CharField(blank=True, help_text="Technical specifications (e.g., '1024x1024 mp4', 'A3 300dpi PDF')", max_length=200)),
                ('category', models.CharField(choices=[('screen', 'Screen/LED'), ('print', 'Print Material'), ('social', 'Social Media'), ('other', 'Other')], default='other', help_text='Category of deliverable', max_length=20)),
                ('is_default', models.BooleanField(default=True, help_text='If true, auto-added to new events for the linked bar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(blank=True, help_text="If set, this template is specific to this bar's hardware", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_templates', to='venues.bar')),
            ],
            options={
                'verbose_name': 'Deliverable Template',
                'verbose_name_plural': 'Deliverable Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event (e.g., 'DJ Night with Guest Star')", max_length=200)),
                ('date', models.DateField(help_text='Date of the event')),
                ('description', models.TextField(blank=True, help_text='Event description and notes')),
                ('brief', models.TextField(blank=True, help_text='Creative brief for designers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bars', models.ManyToManyField(help_text='Bars where this event takes place', related_name='events', to='venues.bar')),
                ('created_by', models.ForeignKey(help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, help_text='Theme period for this event (auto-selected if not set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='planning.themeperiod')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('changes', 'Changes Requested'), ('approved', 'Approved')], default='todo', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Can disable if not needed for this specific event')),
                ('notes', models.TextField(blank=True, help_text='Notes or feedback about this deliverable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for this deliverable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='planning.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_deliverables', to='planning.deliverabletemplate')),
            ],
            options={
                'verbose_name': 'Event Deliverable',
                'verbose_name_plural': 'Event Deliverables',
                'ordering': ['template__category', 'template__name'],
                'unique_together': {('event', 'template')},
            },
        ),
    ]
