# Generated by Django 6.0 on 2026-01-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_deliverabletemplate_event_eventdeliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdeliverable',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Highlight this deliverable in the event panel'),
        ),
    ]
