# Generated by Django 6.0 on 2026-01-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_add_is_starred_to_deliverable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverabletemplate',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='deliverabletemplate',
            name='is_default',
        ),
        migrations.AddField(
            model_name='deliverabletemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is currently in use'),
        ),
        migrations.AlterField(
            model_name='deliverabletemplate',
            name='name',
            field=models.CharField(help_text="Name of the deliverable (e.g., 'Cube LED Video', 'Poster A3')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverabletemplate',
            name='specs',
            field=models.CharField(blank=True, help_text="Technical specifications (e.g., '960x192 mp4', 'A3 300dpi PDF')", max_length=200),
        ),
    ]
