# Generated by Django 6.0 on 2026-01-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bar/venue', max_length=100)),
                ('location', models.CharField(blank=True, help_text='City or address of the venue', max_length=200)),
                ('hardware_specs', models.JSONField(blank=True, default=dict, help_text='JSON containing screen and print specifications')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bar is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bar',
                'verbose_name_plural': 'Bars',
                'ordering': ['name'],
            },
        ),
    ]
