# Generated by Django 6.0 on 2026-01-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('screen', 'Screen / Display'), ('print', 'Print Material'), ('deco', 'Decoration Idea'), ('uniform', 'Uniform Idea')], default='screen', max_length=20)),
                ('name', models.CharField(help_text="Name of the item (e.g., 'Main LED Wall', 'Staff Polo')", max_length=100)),
                ('specs', models.CharField(blank=True, help_text="Specifications (e.g., '1920x1080 mp4', 'A3 300dpi pdf')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or description')),
                ('reference_image', models.ImageField(blank=True, help_text='Reference image for decoration or uniform ideas', null=True, upload_to='hardware_refs/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_items', to='venues.bar')),
            ],
            options={
                'verbose_name': 'Hardware Item',
                'verbose_name_plural': 'Hardware Items',
                'ordering': ['bar', 'category', 'name'],
            },
        ),
    ]
