# Generated by Django 6.0 on 2026-01-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_add_hardwareitem_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwareitem',
            options={'ordering': ['name'], 'verbose_name': 'Hardware Item', 'verbose_name_plural': 'Hardware Items'},
        ),
        migrations.RemoveField(
            model_name='bar',
            name='hardware_specs',
        ),
        migrations.RemoveField(
            model_name='hardwareitem',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='hardwareitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hardwareitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hardwareitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hardwareitem',
            name='reference_image',
        ),
        migrations.AddField(
            model_name='bar',
            name='hardware',
            field=models.ManyToManyField(blank=True, help_text='Hardware items available at this bar', related_name='bars', to='venues.hardwareitem'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='name',
            field=models.CharField(help_text="Name of the hardware (e.g., 'Cube LED', 'Giant LED')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='specs',
            field=models.CharField(blank=True, help_text="Optional specs (e.g., '960x192 mp4')", max_length=200),
        ),
    ]
